
spring:
  #数据库
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_learn?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #整合thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,file:F://video

server:
  port: 9999
