spring:
#   数据库
#  datasource:
#    username: root
#    password: 123
#    url: jdbc:mysql://localhost:3306/boot_crm?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#   整合thymeleaf
  thymeleaf:
    cache: false
    check-template-location: true
    content-type: text/html
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  mvc:
    format:
      date: yyyy-MM-dd
  web:
    resources:
      static-locations: classpath:/static/,file:F://video

# spring security
  security:
    user:
      name: mk
      password: 123


server:
  port: 9999
debug: true


